# Generated by Django 5.1.7 on 2026-09-08 16:54

import apps.quotes.m4_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
        ('shipments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrule',
            name='approver_role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer / Shipper'), ('FREIGHT_AGENT', 'Freight Agent / Operations'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('BROKER', 'Freight Broker'), ('SENIOR_BROKER', 'Senior Broker'), ('PRICING_MANAGER', 'Pricing Manager'), ('OPERATIONS', 'Operations Lead'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('EXECUTIVE', 'Executive Management'), ('COMPANY_MANAGER', 'Freight Company Manager'), ('COMPANY_AGENT', 'Company Verification Agent'), ('ADMIN', 'System Administrator')], default='SENIOR_BROKER', max_length=30),
        ),
        migrations.AlterField(
            model_name='quoteapproval',
            name='approver_role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer / Shipper'), ('FREIGHT_AGENT', 'Freight Agent / Operations'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('BROKER', 'Freight Broker'), ('SENIOR_BROKER', 'Senior Broker'), ('PRICING_MANAGER', 'Pricing Manager'), ('OPERATIONS', 'Operations Lead'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('EXECUTIVE', 'Executive Management'), ('COMPANY_MANAGER', 'Freight Company Manager'), ('COMPANY_AGENT', 'Company Verification Agent'), ('ADMIN', 'System Administrator')], default='SENIOR_BROKER', max_length=30),
        ),
        migrations.CreateModel(
            name='FreightCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.CharField(db_index=True, default=apps.quotes.m4_models.generate_company_id, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('license_no', models.CharField(blank=True, default='', max_length=100)),
                ('modes', models.JSONField(default=list, help_text="Supported modes e.g. ['Ocean', 'Air', 'Road', 'Rail']")),
                ('contact_email', models.EmailField(db_index=True, max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Admin Verification'), ('APPROVED', 'Approved by Admin'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING_VERIFICATION', max_length=30)),
                ('is_eligible', models.BooleanField(default=False, help_text='Eligible to be recommended to customers when verified & approved')),
                ('rating', models.DecimalField(decimal_places=1, default=4.8, max_digits=3)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyQuoteOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('origin', models.CharField(default='Chennai, India', max_length=150)),
                ('destination', models.CharField(default='Rotterdam, Netherlands', max_length=150)),
                ('mode', models.CharField(default='Sea Freight', max_length=50)),
                ('container', models.CharField(default='40 FT', max_length=50)),
                ('cargo', models.CharField(default='Electronics', max_length=150)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=5000, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=85000, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('transit_days', models.IntegerField(default=24)),
                ('risk_level', models.CharField(default='Low', max_length=20)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m4_quote_options', to='shipments.shipment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_options', to='quotes.freightcompany')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_role', models.CharField(choices=[('MANAGER', 'Company Manager'), ('AGENT', 'Verification Agent')], default='AGENT', max_length=20)),
                ('agent_code', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_agent_profile', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='quotes.freightcompany')),
            ],
        ),
        migrations.CreateModel(
            name='M4Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('notification_type', models.CharField(default='WORKFLOW_UPDATE', max_length=50)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='quotes.freightcompany')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='m4_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selection_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('customer_name', models.CharField(default='ABC Electronics Pvt Ltd', max_length=255)),
                ('selected_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(choices=[('QUOTE_OPTIONS_AVAILABLE', 'Options Ready'), ('QUOTE_SELECTED', 'Customer Selected Quote'), ('PENDING_COMPANY_VERIFICATION', 'Pending Company Verification'), ('UNDER_VERIFICATION', 'Under Agent Verification'), ('AWAITING_CUSTOMER_INFO', 'Awaiting Customer Info'), ('REVISION_PENDING_CUSTOMER', 'Revision Pending Customer Review'), ('APPROVED', 'Company Approved'), ('REJECTED', 'Company Rejected'), ('REVISION_ACCEPTED', 'Customer Accepted Revision'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('RESELECT_QUOTE', 'Customer Reselect Quote')], db_index=True, default='PENDING_COMPANY_VERIFICATION', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='quotes.freightcompany')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='m4_quote_selections', to=settings.AUTH_USER_MODEL)),
                ('quote_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='quotes.companyquoteoption')),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_selections', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('revised_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('original_eta_days', models.IntegerField(default=28)),
                ('revised_eta_days', models.IntegerField(default=28)),
                ('reason', models.TextField(help_text='Reason for price or terms modification e.g. Fuel surcharge increase')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Customer Acceptance'), ('ACCEPTED', 'Accepted by Customer'), ('REJECTED', 'Rejected by Customer')], default='PENDING', max_length=20)),
                ('customer_response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='quotes.quoteselection')),
            ],
        ),
        migrations.CreateModel(
            name='M4StatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(max_length=40)),
                ('new_status', models.CharField(max_length=40)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='quotes.quoteselection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_reference', models.CharField(db_index=True, default=apps.quotes.m4_models.generate_booking_reference, max_length=30, unique=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('status', models.CharField(choices=[('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled')], db_index=True, default='BOOKING_CONFIRMED', max_length=30)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='shipments.shipment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='quotes.freightcompany')),
                ('selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='quotes.quoteselection')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUOTE_OPTIONS_AVAILABLE', 'Options Ready'), ('QUOTE_SELECTED', 'Customer Selected Quote'), ('PENDING_COMPANY_VERIFICATION', 'Pending Company Verification'), ('UNDER_VERIFICATION', 'Under Agent Verification'), ('AWAITING_CUSTOMER_INFO', 'Awaiting Customer Info'), ('REVISION_PENDING_CUSTOMER', 'Revision Pending Customer Review'), ('APPROVED', 'Company Approved'), ('REJECTED', 'Company Rejected'), ('REVISION_ACCEPTED', 'Customer Accepted Revision'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('RESELECT_QUOTE', 'Customer Reselect Quote')], default='PENDING_COMPANY_VERIFICATION', max_length=40)),
                ('checklist', models.JSONField(default=dict, help_text='Stores checklist items: shipment, cargo, capacity, route, schedule, documents, commercial, risk, validity')),
                ('remarks', models.TextField(blank=True, default='')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_verifications', to=settings.AUTH_USER_MODEL)),
                ('selection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_request', to='quotes.quoteselection')),
            ],
        ),
    ]
