# Generated by Django 5.1.7 on 2026-09-08 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer / Shipper'), ('FREIGHT_AGENT', 'Freight Agent / Operations'), ('CUSTOMS_OFFICER', 'Customs Officer'), ('BROKER', 'Freight Broker'), ('SENIOR_BROKER', 'Senior Broker'), ('PRICING_MANAGER', 'Pricing Manager'), ('OPERATIONS', 'Operations Lead'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('EXECUTIVE', 'Executive Management'), ('COMPANY_MANAGER', 'Freight Company Manager'), ('COMPANY_AGENT', 'Company Verification Agent'), ('ADMIN', 'System Administrator')], db_index=True, default='CUSTOMER', max_length=30),
        ),
    ]
